name: Intelligent Software Engineering
name_zh: 智能软件工程
name_en: Intelligent Software Engineering
default_lang: zh-CN
url: "https://tjluo-ucas.github.io"
author: Tiejian Luo
email: tjluo@ucas.ac.cn
school: 中国科学院大学
department: 计算机科学与技术学院
teacher: 罗铁坚
github: https://github.com/tjluo-ucas/ase
resume_site: https://github.com/tiejianluo
baseurl: "/ase"
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      lang: zh-CN

